apiVersion: v1
kind: LimitRange
metadata:
  name: mem-limit-range
  namespace: quota-test
spec:
  limits:
  - default:
      memory: 50Gi
      cpu: 5
    defaultRequest:
      memory: 1Gi
      cpu: 1
    type: Container
