apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resource
  namespace: quota-test 
spec:
  hard:
    pods: "2"
    requests.cpu: "20"
    requests.memory: 100Gi
    limits.cpu: "40"
    limits.memory: 200Gi
